# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # or latest stable release
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@172.26.244.181 'bash -s' << 'ENDSSH'
        cd /path/to/your/project
        git pull origin main
        npm install --production
        pm2 restart all
        ENDSSH
